overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  cookie@<0.7.0: '>=0.7.0'
  esbuild@<=0.24.2: '>=0.25.0'
  estree-util-value-to-estree@<3.3.3: '>=3.3.3'
  path-to-regexp@>=4.0.0 <6.3.0: '>=6.3.0'
  semver@>=6.0.0 <6.3.1: '>=6.3.1'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
